/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user with email and password.
         *
         *     Validates password requirements, checks for duplicate emails,
         *     creates user with hashed password, and returns JWT cookie.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email and password.
         *
         *     Verifies credentials, generates JWT, and sets HTTP-only cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description Initiate Google OAuth flow.
         */
        get: operations["google_login_api_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Handle Google OAuth callback.
         */
        get: operations["google_callback_api_auth_callback_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discord Login
         * @description Initiate Discord OAuth flow.
         */
        get: operations["discord_login_api_auth_discord_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discord Callback
         * @description Handle Discord OAuth callback.
         */
        get: operations["discord_callback_api_auth_callback_discord_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current authenticated user.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout current user by clearing cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sops
         * @description List all SOPs for the current user.
         *
         *     Args:
         *         current_user: Current authenticated user
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         List of SOPListItemSchema
         */
        get: operations["list_sops_api_v1_sops_get"];
        put?: never;
        /**
         * Upload And Structure Sop
         * @description Upload and structure a new SOP.
         *
         *     Accepts optional image files and/or text content, uses AI to structure the SOP.
         *     At least one of images or text_content must be provided.
         *
         *     Args:
         *         title: SOP title
         *         images: Optional list of image files
         *         text_content: Optional text content
         *         current_user: Current authenticated user
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         UploadSOPResponse with structured SOP ID
         *
         *     Raises:
         *         HTTPException: If upload or structuring fails, or if neither images nor text provided
         */
        post: operations["upload_and_structure_sop_api_v1_sops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sops/{sop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sop
         * @description Get SOP details by ID.
         *
         *     Args:
         *         sop_id: SOP ID
         *         current_user: Current authenticated user
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         SOPSchema
         *
         *     Raises:
         *         HTTPException: If SOP not found or user not authorized
         */
        get: operations["get_sop_api_v1_sops__sop_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Sop
         * @description Soft delete an SOP.
         *
         *     Args:
         *         sop_id: SOP ID
         *         current_user: Current authenticated user
         *         sop_repo: SOP repository
         *
         *     Raises:
         *         HTTPException: If SOP not found or user not authorized
         */
        delete: operations["delete_sop_api_v1_sops__sop_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all sessions for the current user.
         *
         *     Args:
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *         include_aborted: Whether to include aborted sessions
         *
         *     Returns:
         *         List of WorkSessionSchema
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /**
         * Start Session
         * @description Start a new work session.
         *
         *     Args:
         *         request: Start session request
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         StartSessionResponse with session and first step
         *
         *     Raises:
         *         HTTPException: If SOP not found, not structured, or worker has active session
         */
        post: operations["start_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Session
         * @description Get the current active session for the authenticated user.
         *
         *     Args:
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         WorkSessionSchema if active session exists, None otherwise
         */
        get: operations["get_current_session_api_v1_sessions_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get session details by ID.
         *
         *     Args:
         *         session_id: Session ID
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         WorkSessionSchema
         *
         *     Raises:
         *         HTTPException: If session not found or user not authorized
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Session
         * @description Mark a session as complete.
         *
         *     Args:
         *         session_id: Session ID
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         CompleteSessionResponse
         *
         *     Raises:
         *         HTTPException: If session not found, not authorized, or cannot be completed
         */
        post: operations["complete_session_api_v1_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Session
         * @description Pause an in-progress session.
         */
        post: operations["pause_session_api_v1_sessions__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Session
         * @description Resume a paused session.
         */
        post: operations["resume_session_api_v1_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort Session
         * @description Abort a session permanently.
         */
        post: operations["abort_session_api_v1_sessions__session_id__abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Safety Check
         * @description Execute a safety check with image and audio verification.
         *
         *     Args:
         *         request: Execute check request with base64-encoded image and audio
         *         current_user: Current authenticated user
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         ExecuteCheckResponse with result, feedback text and audio
         *
         *     Raises:
         *         HTTPException: If validation fails or check execution fails
         */
        post: operations["execute_safety_check_api_v1_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks/{check_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Override Check
         * @description Override a safety check result (supervisor only).
         *
         *     Args:
         *         check_id: Check ID
         *         request: Override request with reason
         *         current_user: Current authenticated user (must be supervisor)
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         OverrideCheckResponse
         *
         *     Raises:
         *         HTTPException: If check not found, not authorized, or override fails
         */
        post: operations["override_check_api_v1_checks__check_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Sessions
         * @description List sessions for audit review (supervisor only).
         *
         *     Args:
         *         status_filter: Filter by status (default: completed)
         *         current_user: Current authenticated user (supervisor)
         *         session_repo: Session repository
         *         sop_repo: SOP repository
         *
         *     Returns:
         *         List of AuditSessionListItem
         *
         *     Raises:
         *         HTTPException: If not authorized
         */
        get: operations["list_audit_sessions_api_v1_audit_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Session
         * @description Get full audit trail for a session (supervisor only).
         *
         *     Args:
         *         session_id: Session ID
         *         current_user: Current authenticated user (supervisor)
         *         session_repo: Session repository
         *
         *     Returns:
         *         WorkSessionSchema with full audit trail
         *
         *     Raises:
         *         HTTPException: If session not found or not authorized
         */
        get: operations["get_audit_session_api_v1_audit_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/sessions/{session_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Session
         * @description Approve a completed session (supervisor only).
         *
         *     Args:
         *         session_id: Session ID
         *         current_user: Current authenticated user (supervisor)
         *         session_repo: Session repository
         *
         *     Returns:
         *         ApproveSessionResponse
         *
         *     Raises:
         *         HTTPException: If session not found, not authorized, or cannot be approved
         */
        post: operations["approve_session_api_v1_audit_sessions__session_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/sessions/{session_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Session
         * @description Reject a completed session (supervisor only).
         *
         *     Args:
         *         session_id: Session ID
         *         request: Reject request with reason
         *         current_user: Current authenticated user (supervisor)
         *         session_repo: Session repository
         *
         *     Returns:
         *         RejectSessionResponse
         *
         *     Raises:
         *         HTTPException: If session not found, not authorized, or cannot be rejected
         */
        post: operations["reject_session_api_v1_audit_sessions__session_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint with database connectivity verification.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbortSessionRequest
         * @description Request to abort a session.
         */
        AbortSessionRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * AbortSessionResponse
         * @description Response from aborting a session.
         */
        AbortSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
        };
        /**
         * ApproveSessionResponse
         * @description Response from approving a session.
         */
        ApproveSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
            /** Approved */
            approved: boolean;
        };
        /**
         * AuditSessionListItem
         * @description Audit session list item.
         */
        AuditSessionListItem: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Sop Title */
            sop_title: string;
            /**
             * Worker Id
             * Format: uuid
             */
            worker_id: string;
            /** Status */
            status: string;
            /** Completed At */
            completed_at: string | null;
            /** Check Count */
            check_count: number;
            /** Failed Check Count */
            failed_check_count: number;
        };
        /** Body_upload_and_structure_sop_api_v1_sops_post */
        Body_upload_and_structure_sop_api_v1_sops_post: {
            /** Title */
            title: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /** Text Content */
            text_content?: string | null;
        };
        /**
         * CompleteSessionResponse
         * @description Response from completing a session.
         */
        CompleteSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
            /** Completed */
            completed: boolean;
        };
        /**
         * ExecuteCheckRequest
         * @description Request to execute a safety check.
         */
        ExecuteCheckRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Step Id
             * Format: uuid
             */
            step_id: string;
            /** Image Base64 */
            image_base64: string;
            /** Audio Base64 */
            audio_base64?: string | null;
            /** Audio Transcript */
            audio_transcript?: string | null;
        };
        /**
         * ExecuteCheckResponse
         * @description Response from executing a safety check.
         */
        ExecuteCheckResponse: {
            /** Result */
            result: string;
            /** Feedback Text */
            feedback_text: string;
            /** Feedback Audio Base64 */
            feedback_audio_base64: string;
            /** Confidence Score */
            confidence_score: number;
            /** Needs Review */
            needs_review: boolean;
            /** Next Step Id */
            next_step_id: string | null;
            /** Session Updated */
            session_updated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HazardSchema
         * @description Hazard schema.
         */
        HazardSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Description */
            description: string;
            /** Severity */
            severity: string;
            /** Mitigation */
            mitigation?: string | null;
        };
        /**
         * LoginRequest
         * @description Login request model.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OverrideCheckRequest
         * @description Request to override a safety check.
         */
        OverrideCheckRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * OverrideCheckResponse
         * @description Response from overriding a check.
         */
        OverrideCheckResponse: {
            /**
             * Check Id
             * Format: uuid
             */
            check_id: string;
            /** Overridden */
            overridden: boolean;
        };
        /**
         * PauseSessionResponse
         * @description Response from pausing a session.
         */
        PauseSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
        };
        /**
         * RegisterRequest
         * @description Registration request model.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /**
         * RejectSessionRequest
         * @description Request to reject a session.
         */
        RejectSessionRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * RejectSessionResponse
         * @description Response from rejecting a session.
         */
        RejectSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
            /** Rejected */
            rejected: boolean;
        };
        /**
         * ResumeSessionResponse
         * @description Response from resuming a session.
         */
        ResumeSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
        };
        /**
         * SOPListItemSchema
         * @description SOP list item schema (without tasks).
         */
        SOPListItemSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Task Count */
            task_count: number;
            /** Step Count */
            step_count: number;
        };
        /**
         * SOPSchema
         * @description SOP response schema.
         */
        SOPSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskSchema"][];
        };
        /**
         * SafetyCheckSchema
         * @description Safety check schema.
         */
        SafetyCheckSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Step Id
             * Format: uuid
             */
            step_id: string;
            /** Result */
            result: string;
            /** Feedback Text */
            feedback_text: string;
            /** Confidence Score */
            confidence_score?: number | null;
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Override Reason */
            override_reason?: string | null;
            /** Override By */
            override_by?: string | null;
        };
        /**
         * StartSessionRequest
         * @description Request to start a new work session.
         */
        StartSessionRequest: {
            /**
             * Sop Id
             * Format: uuid
             */
            sop_id: string;
        };
        /**
         * StartSessionResponse
         * @description Response from starting a session.
         */
        StartSessionResponse: {
            session: components["schemas"]["WorkSessionSchema"];
            /** First Step Id */
            first_step_id: string | null;
        };
        /**
         * StepSchema
         * @description Step schema.
         */
        StepSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Description */
            description: string;
            /** Order Index */
            order_index: number;
            /** Expected Action */
            expected_action?: string | null;
            /** Expected Result */
            expected_result?: string | null;
            /**
             * Hazards
             * @default []
             */
            hazards: components["schemas"]["HazardSchema"][];
        };
        /**
         * TaskSchema
         * @description Task schema.
         */
        TaskSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Order Index */
            order_index: number;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepSchema"][];
        };
        /**
         * UploadSOPResponse
         * @description Response from uploading an SOP.
         */
        UploadSOPResponse: {
            /**
             * Sop Id
             * Format: uuid
             */
            sop_id: string;
            /** Title */
            title: string;
            /** Success */
            success: boolean;
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * UserResponse
         * @description User response model.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkSessionSchema
         * @description Work session response schema.
         */
        WorkSessionSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sop Id
             * Format: uuid
             */
            sop_id: string;
            /** Sop Title */
            sop_title: string;
            /**
             * Worker Id
             * Format: uuid
             */
            worker_id: string;
            /** Status */
            status: string;
            /** Current Step Id */
            current_step_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Paused At */
            paused_at?: string | null;
            /** Aborted At */
            aborted_at?: string | null;
            /** Abort Reason */
            abort_reason?: string | null;
            /** Locked */
            locked: boolean;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["SafetyCheckSchema"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_api_auth_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_api_auth_callback_google_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discord_login_api_auth_discord_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discord_callback_api_auth_callback_discord_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sops_api_v1_sops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPListItemSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_and_structure_sop_api_v1_sops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_and_structure_sop_api_v1_sops_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSOPResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sop_api_v1_sops__sop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sop_api_v1_sops__sop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                include_aborted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSessionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_session_api_v1_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSessionSchema"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSessionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_v1_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_session_api_v1_sessions__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_session_api_v1_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_session_api_v1_sessions__session_id__abort_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbortSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbortSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_safety_check_api_v1_checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_check_api_v1_checks__check_id__override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_sessions_api_v1_audit_sessions_get: {
        parameters: {
            query?: {
                status_filter?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSessionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_session_api_v1_audit_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSessionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_session_api_v1_audit_sessions__session_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_session_api_v1_audit_sessions__session_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
